name: Sample GHA Workflow for PPC 

on: [ workflow_dispatch, push ]

jobs:     
  power_job:
    name: amd Job
    runs-on: ubuntu-latest
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          groups
          id
          whoami
          ls -la
          cat /etc/hosts
          nproc
          lspci
