name: Sample GHA Workflow for PPC 

on: [ workflow_dispatch, push ]

jobs:     
  power_job:
    name: Power Job
    runs-on: self-hosted
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          groups
          id
          whoami
